<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>@@title :: George Merlocco</title>
    <meta name="description" content="@@description">
    <meta name="author" content="George Merlocco">

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- include:css(list:vendorCSSlist) -->
    <!-- include:css(css/**/*.css) -->

</head>

<body>