<nav class="pushy pushy-left">
    <ul>
        <li><a href="/index.html" class="@@activeNavHome">Home</a></li>
        <li><a href="/portfolio.html" class="@@activeNavPortfolio">Portfolio</a></li>
        <li><a href="#" class="@@activeNav">Tours</a></li>
        <li><a href="#" class="@@activeNav">Photos</a></li>
        <li><a href="#" class="@@activeNav">Bio</a></li>
        <li><a href="#" class="@@activeNav">Contact</a></li>
    </ul>
</nav>

<!-- Site Overlay -->
<div class="site-overlay"></div>