<nav>
    <ul>
        <li><a href="/home.html" class="@@activeNavHome">Home</a></li>
        <li><a href="/portfolio.html" class="@@activeNavPortfolio">Portfolio</a></li>
        <li><a href="#" class="@@activeNav">Tours</a></li>
        <li><a href="#" class="@@activeNav">Photos</a></li>
        <li><a href="#" class="@@activeNav">Bio</a></li>
        <li><a href="#" class="@@activeNav">Contact</a></li>
    </ul>
</nav>